import { FormLogin } from "@/modules/Auth/components";
import { Counter } from "@/modules/Counter/components";
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

const Container = styled.div`
  padding: 0 2rem;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormLogin />
      <Counter />
    </Container>
  );
};

export default Home;
