name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: brandon-gs/storymash-api
          path: ./storymash-api
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install server dependencies
        working-directory: ./storymash-api
        run: npm ci

      - run: npm i -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn prettier
      - run: yarn build

      - name: Run tests with jest
        run: yarn test:ci

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
